export const config = [

    {
        name:'基础组件',
        router:'/pages/base/index/index',
        icon:'base',
    },
    {
        name:'视图组件',
        router:'/pages/view/index/index',
        icon:'view',
    },
    {
        name:'布局组件',
        router:'/pages/layout/index/index',
        icon:'laout',
    },
    {
        name:'表单组件',
        router:'/pages/form/index/index',
        icon:'form',
    },
    {
        name:'导航组件',
        router:'/pages/navigation/index/index',
        icon:'nav',
    },
    {
        name:'操作反馈',
        router:'/pages/feedback/index/index',
        icon:'feedback',
    },
    {
        name:'动画组件',
        router:'/pages/animation/index/index',
        icon:'animation',
    },
    {
        name:'业务组件',
        router:'/pages/business/index/index',
        icon:'busi',
    },
]