module.exports = [
  "appreciate",
  "check",
  "close",
  "edit",
  "emoji",
  "favor",
  "location",
  "roundclose",
  "search",
  "unfold",
  "warn",
  "camera",
  "like",
  "voice",
  "shop",
  "back",
  "list",
  "more",
  "scan",
  "settings",
  "question", "pic", "right", "cart",
  "qrcode", "delete", "home", "lock", "unlock", "goods", "present", "add", "fold", "forward", "share", "searchlist", "service", "sort", "notice", "mark", "attention", "tag", "upload", "my", "mail", "loading",
]
